language: rust
cache: cargo
stages:
    - preliminary
    - base 
    - sanitize 
install: 
    - rustup default stable
    - rustup component add clippy
    - rustup default nightly
    - rustup component add rustfmt
matrix:
    include:
        - name: "formatter"
          rust: 'nightly'
          script: cargo fmt --all -- --check
          stage: preliminary

        - name: "linter"
          rust: 'stable'
          script: cargo clippy --all-features -- -D warnings
          stage: preliminary 

        - name: "build + test"
          rust: 'stable'
          script: cargo build && cargo test
          stage: base

        - name: "build + test"
          rust: 'stable'
          script: cargo build && cargo test
          stage: base
          os: osx

        - name: "address sanitizer"
          rust: 'nightly'
          env: 
            - rustflags="-z sanitizer=address"
            - asan_options="detect_odr_violation=0"
          script: cargo build --all && cargo test --all --target x86_64-unknown-linux-gnu
          stage: sanitize

