language: rust
cache: cargo
stages:
    - format
    - base
    - sanitize 
install: rustup component add rustfmt
matrix:
    include:
        - name: "Check formatting"
          rust: '1.31.0'
          script: cargo fmt --all
          stage: format

        - name: "Base build + test"
          rust: '1.31.0'
          script: cargo build && cargo test
          stage: base

        - name: "Address Sanitizer Test"
          rust: 'nightly'
          env: RUSTFLAGS="-Z sanitizer=address"
          env: ASAN_OPTIONS="detect_odr_violation=0"
          script: cargo build --all && cargo test --all --target x86_64-unknown-linux-gnu
          stage: sanitize
