language: rust
cache: cargo
stages:
    - format
    - base
    - sanitize 
install: rustup component add rustfmt
matrix:
    include:
        - name: "Check formatting"
          rust: 'nightly'
          script: cargo fmt --all
          stage: format

        - name: "base build + test"
          rust: 'nightly'
          script: cargo build && cargo test
          stage: base

        - name: "address sanitizer test"
          rust: 'nightly'
          env: 
            - rustflags="-z sanitizer=address"
            - asan_options="detect_odr_violation=0"
          script: cargo build --all && cargo test --all --target x86_64-unknown-linux-gnu
          stage: sanitize

        - name: "base build + test"
          rust: 'nightly'
          script: cargo build && cargo test
          stage: base
          os: macos

        - name: "address sanitizer test"
          rust: 'nightly'
          env: 
            - rustflags="-z sanitizer=address"
            - asan_options="detect_odr_violation=0"
          script: cargo build --all && cargo test --all --target x86_64-unknown-linux-gnu
          stage: sanitize
          os: macos
