language: rust
cache: cargo
rust:
    - 1.31.0
matrix:
    include:
        # linux
        - name: "Base build + test"
          rust: '1.31.0'
        - name: "Thread Sanitizer Test"
          rust: 'nightly'
          env: RUSTFLAGS="-Z sanitizer=thread"
        - name: "Address Sanitizer Test"
          rust: 'nightly'
          env: RUSTFLAGS="-Z sanitizer=address"
        - name: "Leak Sanitizer Test"
          rust: 'nightly'
          env: RUSTFLAGS="-Z sanitizer=leak"
        - name: "Memory Sanitizer Test"
          rust: 'nightly'
          env: RUSTFLAGS="-Z sanitizer=memory"
        
        # mac os
        - name: "Base build + test"
          rust: '1.31.0'
          os: macos
        - name: "Thread Sanitizer Test"
          rust: 'nightly'
          env: RUSTFLAGS="-Z sanitizer=thread"
          os: macos
        - name: "Address Sanitizer Test"
          rust: 'nightly'
          env: RUSTFLAGS="-Z sanitizer=address"
          os: macos
        - name: "Leak Sanitizer Test"
          rust: 'nightly'
          env: RUSTFLAGS="-Z sanitizer=leak"
          os: macos
        - name: "Memory Sanitizer Test"
          rust: 'nightly'
          env: RUSTFLAGS="-Z sanitizer=memory"
          os: macos

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
