[package]
name = "benchviz_rs"
version = "0.1.0"
authors = ["superfunc <superfunc@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = "1.0.80"
serde_json = "1.0"
serde_derive = "1.0.80"
clap = "2.32.0"
